# Generated by Django 5.2.6 on 2025-10-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidecrewapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
