# Generated by Django 5.2.6 on 2025-10-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidecrewapp', '0002_agent_is_approved_client_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_approved',
        ),
    ]
