# Generated by Django 5.2.6 on 2025-10-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidecrewapp', '0003_remove_agent_is_approved_remove_client_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
