# Generated by Django 5.2.6 on 2025-11-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidecrewapp', '0005_job_jobposting_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location_address',
            field=models.TextField(blank=True, help_text='Auto-filled by map', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
