# Generated by Django 5.2.6 on 2025-11-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidecrewapp', '0006_job_location_address_job_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PENDING_AGENT', 'Pending Agent Approval'), ('OPEN', 'Open (Awaiting Posts)'), ('FILLED', 'Filled'), ('COMPLETED', 'Completed')], default='SEEKING_AGENT', max_length=20),
        ),
    ]
