# Generated by Django 5.2.6 on 2025-11-04 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidecrewapp', '0007_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PROOF_SUBMITTED', 'Proof Submitted'), ('COMPLETED', 'Completed'), ('PROOF_REJECTED', 'Proof Rejected')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_proofs/')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('agent_remarks', models.TextField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_proof', to='sidecrewapp.application')),
            ],
        ),
    ]
