# Generated by Django 5.2.6 on 2025-11-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidecrewapp', '0008_alter_application_status_workproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='worker_payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='client_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
