# Generated by Django 5.2.6 on 2025-11-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidecrewapp', '0010_agent_rating_application_agent_rating_for_worker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
